echo "lines" >> file;
git add file;
git commit -m "Git Rek";
echo "lines" >> file;
git add file;
git commit -m "Bloop till you floop";
echo "lines" >> file;
git add file;
git commit -m "bloop is love, bloop is life";
echo "lines" >> file;
git add file;
git commit -m "Cannot describe this commit";
echo "lines" >> file;
git add file;
git commit -m "Whats an error checker";
echo "lines" >> file;
git add file;
git commit -m "Somebody once told me";
echo "lines" >> file;
git add file;
git commit -m "We are number one, but its git, and my hackathon project";
echo "lines" >> file;
git add file;
git commit -m "git creative";
echo "lines" >> file;
git add file;
git commit -m "Act I Scene I";
echo "lines" >> file;
git add file;
git commit -m "Enter Romeo (javascript)";
echo "lines" >> file;
git add file;
git commit -m "Enter Juiliet (node.js)";
echo "lines" >> file;
git add file;
git commit -m "Act IX Everyone is dead";
echo "lines" >> file;
git add file;
git commit -m "Half way dead, I mean done hackathon";
echo "lines" >> file;
git add file;