touch file;
git add file;
git commit -m "Git Rek";
touch file;
git add file;
git commit -m "Bloop till you floop";
touch file;
git add file;
git commit -m "bloop is love, bloop is life";
touch file;
git add file;
git commit -m "Cannot describe this commit";
touch file;
git add file;
git commit -m "Whats an error checker";
touch file;
git add file;
git commit -m "Somebody once told me";
touch file;
git add file;
git commit -m "We are number one, but its git, and my hackathon project";
touch file;
git add file;
git commit -m "git creative";
touch file;
git add file;
git commit -m "Act I Scene I";
touch file;
git add file;
git commit -m "Enter Romeo (javascript)";
touch file;
git add file;
git commit -m "Enter Juiliet (node.js)";
touch file;
git add file;
git commit -m "Act IX Everyone is dead";
touch file;
git add file;
git commit -m "Half way dead, I mean done hackathon";
touch file;
git add file;